version: "2"
services:
  regtest-mongo:
    container_name: mongo
    image: "mongo:3.2"
    hostname: mongo
    expose:
      - "27017"
    ports:
      - "28017:27017"
    dns: #doesn't seem to work anymore
      - 172.20.0.5
    volumes:
      - ../scripts/docker-compose/resolv.conf:/etc/resolv.conf
      - ../scripts/meteor/delete_collections.sh:/tmp/delete_collections.sh
    networks:
      static-network:
        ipv4_address: 172.20.0.3

  bind:
    container_name: bind
    image: "sameersbn/bind:9.11.3-20180713"
    hostname: ns
    expose:
      - "53"
    ports:
      - "53:53/udp"
      - "10000:10000"
    dns:
      - 172.20.0.5
      - 8.8.8.8
    environment:
      - ROOT_PASSWORD=generated-password
    command: /contrib/scripts/docker-compose/update_bind.sh
    #stdin_open: true
    #tty: true
    volumes:
      - "../:/contrib"
      - ../scripts/docker-compose/resolv.conf:/etc/resolv.conf
    networks:
      static-network:
        ipv4_address: 172.20.0.5

  mail:
    container_name: mail
    image: "esminis/mail-server-postfix-vm-pop3d"
    hostname: mail
    expose:
       - "25"
       - "465"
       - "995"
    ports:
      - "8443:8443"
      - "25:25"
      - "110:110"
      - "465:465"
      - "995:995"
    dns:
      - 172.20.0.5
      - 8.8.8.8
    dns_search: ci-doichain.org
    depends_on:
      - bind
    volumes:
      - "../:/contrib"
      - ../scripts/docker-compose/resolv.conf:/etc/resolv.conf
    command: bash -c 'cp /contrib/scripts/sasl/sasldb2 /etc/ && cp -r /contrib/scripts/tequila/* /opt/tequila/domains/ && chown -R tequila:tequila /opt/tequila/domains && mkdir -p /var/spool/virtual/ci-doichain.org && chown tequila:tequila /var/spool/virtual/ci-doichain.org && service postfix reload && sleep infinity'
    networks:
      static-network:
        ipv4_address: 172.20.0.4

  alice:
    container_name: alice
    image: "doichain/core:dc0.20.1.12" 
    hostname: alice
    ports:
      - "18543:18332"
    expose:
      - "18332"
    environment:
      - REGTEST=true
      - RPC_ALLOW_IP=::/0
      - CONNECTION_NODE=bob
      - RPC_PASSWORD=password
      - DAPP_URL=http://172.20.0.9:3000/
    dns:
      - 172.20.0.5
      - 8.8.8.8
    dns_search: ci-doichain.org
    volumes:
      - ../scripts/docker-compose/resolv.conf:/etc/resolv.conf
    stdin_open: true
    tty: true
    networks:
      static-network:
        ipv4_address: 172.20.0.6

  bob:
    container_name: bob
    image: "doichain/core:dc0.20.1.12" 
    hostname: bob
    ports:
      - "18544:18332"
    expose:
      - "18332"
    environment:
      - REGTEST=true
      - CONNECTION_NODE=alice
      - RPC_ALLOW_IP=::/0
      - RPC_PASSWORD=password
      - DAPP_URL=http://172.20.0.9:4000/
#      - DAPP_URL=http://172.20.0.8:4000 #use this when tests run inside docker
    dns:
      - 172.20.0.5
      - 8.8.8.8
    dns_search: ci-doichain.org
    volumes:
      - ../scripts/docker-compose/resolv.conf:/etc/resolv.conf
    stdin_open: true
    tty: true
    networks:
      static-network:
        ipv4_address: 172.20.0.7

#  regtest:
#    image: "doichain/dapp-only"
#    hostname: regtest
#    #build: .
#    volumes:
#      - ./contrib/scripts/docker-compose/resolv.conf:/etc/resolv.conf
#      - "/var/run/docker.sock:/var/run/docker.sock"
#      - ".:/home/doichain/dapp" #TODO you can enable this during development but not during testing in CI (permission denided)
#    dns:
#      - 172.20.0.5
#      - 8.8.8.8
#    dns_search: ci-doichain.org
#    #&& export MONGO_URL=mongodb://mongo:27017/alice && meteor npm cache verify && meteor npm install && meteor npm run test-d-compose-alice-mocha
#    command: bash -c "./contrib/scripts/meteor/start_dapp.sh && sleep infinity"
#    ports:
#      - "3000:3000"
#      - "4000:4000"
#    expose:
#      - "3000"
#      - "4000"
#    stdin_open: true
#    tty: true
#    privileged: true
#    depends_on:
#      - mongo
#      - alice
#      - bob
#      - bind
#      - mail
#    networks:
#        static-network:
#          ipv4_address: 172.20.0.8

  dockerhost:
    image: qoomon/docker-host
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
#    volumes:
#     - ./contrib/scripts/docker-compose/resolv.conf:/etc/resolv.conf
    restart: on-failure
    expose:
      - "3000"
      - "4000"
    networks:
      static-network:
        ipv4_address: 172.20.0.9

networks:
  static-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
